### ISSUE TITLE
和MBProgressHUD一起使用时会崩溃

### ISSUE THREAD

**Issue by sunq08** [DarkAngel7/UINavigationController-DAPowerfulCustomization#2]
和MBProgressHUD一起使用时一运行直接就崩了

**Comment by DarkAngel7** [comment]
经过测试iOS 9、10、11，我使用最新版本的`MBProgressHUD`，并没有出现崩溃问题。
建议你更新下最新版本的`UINavigationController+DAPowerfulCustomization`。
你也可以排查下Crash时的stack，是否跟你的项目某些页面设置有关。

**Comment by sunq08** [comment]
我试了一下，把hud放到keyWindow上就崩了，放到当前视图的view上就好了，总之多谢了

**Comment by DarkAngel7** [comment]
我看了下，在此说明下：
1、`UINavigationBar`是公用的，想实现每个viewController可以定制不同的appearance，就必须在适当的地方获取vc.navigationItem的所有值，然后根据这些值进行`UINavigationBar`的调整。
2、`UINavigationItem`的属性有可能是在init中设置的，也有可能是在`viewDidLoad`中设置的，那么`UINavigationController`就必须先调用`[vc setNeedsLayout]`确保vc的`viewDidLoad`已经调用，从而获取正确的navigationItem的所有属性。
3、在`viewDidLoad`之后的方法（如`viewWillAppear`等）中设置的navigationItem的属性，在set方法中，navigationItem已经是topItem，代码中也已经做过处理。
4、在`UINavigationController`的`viewDidLoad`中调用`[self.topViewController setNeedsLayout]`时可能会触发topViewController的`viewDidLoad`。如果此时你在topViewController的`viewDidLoad`中把`MBProgressHUD`添加到`keyWindow`上，并且当前的`UINavigationController`正好是`keyWindow`的`rootViewController`，由于此时`[UIApplication sharedApplication].keyWindow`是`nil`，`MBProgressHUD`的`initWithView:`方法会主动抛出异常，so 崩溃了。

解决方案：
以目前的设计来看，很难回避这个问题，毕竟`keyWindow`是在`UINavigationController`之前创建的还是之后无从得知。如果你依然想使用`keyWindow`作为`MBProgressHUD`的`superview`，那在`viewDidLoad`中，添加一点点延迟，如：
```objective-c
dispatch_async(dispatch_get_main_queue(), ^{
      MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:[UIApplication sharedApplication].keyWindow animated:YES];
      hud.....
});
```

**Comment by sunq08** [comment]
受教了，多谢！
