### ISSUE TITLE
[self.navigationController.navigationBar setTranslucent:NO];这个属性设置就不生效了吧。

### ISSUE THREAD

**Issue by caijinming** [DarkAngel7/UINavigationController-DAPowerfulCustomization#3]

**Comment by DarkAngel7** [comment]
可以兼容这个属性，但是Translucent = NO的话，导航栏默认无背景色，为nil，如果backgroundViewAlpha = 0，则导航栏会成为黑色，此时需要去设置导航栏自己的背景色。最新的版本1.4.1里已经兼容了此属性，你可以测试下。

**Comment by caijinming** [comment]
嗯！我试试，对了目前没有单独隐藏导航栏底部的黑线的属性吧。
